spring:
  application:
    name: springboot2-prometheus
server:
  port: 8088

#1. 打开所有 Actuator 服务
#2. 将应用名称添加到计量器的 tag 中去, 以便 Prometheus 根据应用名区分不同服务
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}